### ISSUE TITLE
Allow $schema in the plugin.json

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/plugin-validator#1]
Current `plugin.schema.json` doesn't have option to enter `$schema`. Allowing `$schema` will enhance IDEs to autocomplete and lint the `plugin.json` file. 

#### **With schema**: ( Autocomplete and Linting ) 

![image](https://user-images.githubusercontent.com/153843/90332485-39cc8200-dfb5-11ea-9e2e-3607a339b1b2.png)
![image](https://user-images.githubusercontent.com/153843/90332193-f709aa80-dfb2-11ea-9831-b6a9dfff5e5c.png)
![image](https://user-images.githubusercontent.com/153843/90332328-cece7b80-dfb3-11ea-9b0f-e471f06e22c6.png)
![image](https://user-images.githubusercontent.com/153843/90332225-16a0d300-dfb3-11ea-8cc7-7b62dc67f372.png)

#### **Without schema**: ( No autocomplete, No Lint )

![image](https://user-images.githubusercontent.com/153843/90332235-24565880-dfb3-11ea-9cc4-715f21f56345.png)
![image](https://user-images.githubusercontent.com/153843/90332449-db9f9f00-dfb4-11ea-8a58-c08ea1af80c8.png)

**Comment by yesoreyeram** [comment]
If the `$schema` is allowed, then developers can enter `https://raw.githubusercontent.com/grafana/plugin-validator/master/config/plugin.schema.json` as their `$schema` to validate and lint the `plugin.json` file with the latest guidelines.

**Comment by marcusolsson** [comment]
Closing as this has already been added.
