### ISSUE TITLE
couldn't extract plugin archive: zip: not a valid zip file

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/plugin-validator#104]
When I execute the check plug-in command, docker run -- pull=always grafana/plugin-validator-cli http://xxx.zip Or docker run -- pull=always grafana/plugin-validator-cli - sourceCodeUri http://xxx http://xxxx/xx.zip There will be the following errors

<img width="628" alt="image" src="https://user-images.githubusercontent.com/76942485/224906039-13b0ebef-436f-492d-9b68-0a0f2c04875a.png">

**Comment by eh-am** [comment]
Hi! Based on the error message, it couldn't extract the zip file https://github.com/grafana/plugin-validator/blob/6da5c1ca3bc71cb35be50264dfa8e1d3d3c2920e/pkg/cmd/plugincheck2/main.go#L60-L66

So worth checking, is it a real zip file? How are you packaging it?

Here's what I've used in my projects, which seems to work fine.
```bash
mv dist $MY-PLUGIN-ID
zip $MY-PLUGIN-ID.zip $MY-PLUGIN-ID -r
```

**Comment by academo** [comment]
Hi @CloudWise-Lukemiao are you still having problems with this? I agree with @eh-am where it looks your zip file was corrupted or incorrectly packaged.
