### ISSUE TITLE
Allow absolute screenshot URLs in plugin.json

### ISSUE THREAD

**Issue by 6nv** [grafana/plugin-validator#106]
https://github.com/grafana/plugin-validator/blob/63f422357cacb41aedd56590fe19ecd8dc0fea0b/pkg/analysis/passes/metadatapaths/metadatapaths.go#L88

My explanation can be found in [this forum post](https://community.grafana.com/t/adding-screenshots-but-dont-package-them/83035). In summary, I am getting this error because I am putting absolute links to my screenshots in `plugin.json`. I believe that this restriction should be lifted for screenshots, because when relative paths are used, the screenshots are packaged in with the plugin and get an asset size limit warning.

**Comment by 6nv** [comment]
I found a temporary fix. Disable the `metadatapaths` analyzer. Related PR: https://github.com/grafana/plugin-validator/pull/107

**Comment by academo** [comment]
Hi @6nv .

So far we require the screenshot to use relative urls as this is the way our Grafana Catalog works. This is not something we can change in the validator only.
