### ISSUE TITLE
Add some flexibility when checking tokenAuth url

### ISSUE THREAD

**Issue by sbouchex** [grafana/plugin-validator#11]
My tokenAuth url is defined as :
`"url": "{{ .JsonData.urlRoot }}/SSO/oauth2/token"`

But the tool is rejecting the url as the url is not starting by http or https. The error is:
`"details": "`routes.0.tokenAuth.url`: Does not match format 'uri'\n\nFor more information, refer to the [reference documentation]`

In my case, the urlRoot is defined in another variable depending on the authentication server.

How can I add some flexibility when checking tokenAuth url ?

**Comment by marcusolsson** [comment]
You're correct. Since the routes are templates, they most likely won't be proper URIs. We should update the [schema](https://github.com/grafana/grafana/blob/f5d1fa48ca4a028b0f8996a0c4e7848635fc2579/docs/sources/developers/plugins/plugin.schema.json#L361) to reflect this.

**Comment by marcusolsson** [comment]
I've opened a PR that fixes this: https://github.com/grafana/grafana/pull/31633
