### ISSUE TITLE
version pattern should match pattern used by check-repo-update

### ISSUE THREAD

**Issue by sbouchex** [grafana/plugin-validator#12]
If the plug in version is 2021.03.0, it should rejected as this version will be rejected afterwards by check-repo-update (when creating a PR)

The regexp should be something like :` ^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*$|\\%VERSION\\%)` to validate the version

**Comment by marcusolsson** [comment]
Thanks! Could you open the pull request and change the schema in the grafana repo (which this tool downloads)?

https://github.com/grafana/grafana/blob/master/docs/sources/developers/plugins/plugin.schema.json

**Comment by sbouchex** [comment]
@marcusolsson PR done
