### ISSUE TITLE
New analyzer: detect usage of go-sdk and version for backend plugins

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-validator#126]
Provide a new analyzer to detect whether the go-sdk is being used for a backend component and which version is being used. 

It _could_ check for `backend=true` in the `plugin.json` file. If yes, scan for a go.mod file in the project and check the version declared there. 

To start with, it should warn if the sdk is not being used and if the version is not latest (as well as printing "we recommended updating to the current version <version>".

In the future we can consider failing if the sdk is not being used and if the version is significantly out of date

**Comment by academo** [comment]
Solved with https://github.com/grafana/plugin-validator/pull/192

**Comment by sympatheticmoose** [comment]
@academo the linked PR doesn't seem to address the version and hasn't been added to the readme https://github.com/grafana/plugin-validator?tab=readme-ov-file#analyzers
