### ISSUE TITLE
Validate plugin signature type if present

### ISSUE THREAD

**Issue by academo** [grafana/plugin-validator#134]
Make sure community or commercially signed plugins don't have a rootUrl restriction.

**Comment by xnyo** [comment]
@academo There's also this check that is not implemented by `plugin-validator` but it's implemented in Grafana:

https://github.com/grafana/grafana/blob/ad63400a5417c5b53702149cd0467be97d89386a/pkg/plugins/manager/signature/manifest.go#L224

(the plugin shouldn't have any files that are not in MANIFEST.txt)

The other checks are implemented.

**Comment by academo** [comment]
@xnyo we have that check in place https://github.com/grafana/plugin-validator/blob/main/pkg/analysis/passes/manifest/manifest.go#L67
