### ISSUE TITLE
Upgrade semgrep to latest version

### ISSUE THREAD

**Issue by academo** [grafana/plugin-validator#135]
In https://github.com/grafana/plugin-validator/pull/133/ we had to lock the semgrep version to 1.28 because the newer version (>=1.38) is not working as expected.

We should research what's not working in this new version and patch it so we can keep using the updated tool.

**Comment by briangann** [comment]
looks like drone is not using semgrep at all and skipping those tests

**Comment by academo** [comment]
@briangann from which CI are these logs?

**Comment by briangann** [comment]
> ```shell
> TestAccessEnvVariable
> ```

See https://drone.grafana.net/grafana/plugin-validator/194/1/2

Line 316 (expand all logs first)

**Comment by academo** [comment]
@briangann I looked into it. that's expected. What drone does is build the Docker image (on main merge).

The docker image will have semgrep installed and the validator binary, to build the validator binary, the drone runner needs to run the tests which skip semgrep because the drone runner doesn't have it installed. That doesn't affect the final docker image that will have both the binary and semgrep.

nevertheless, the github action that runs on PRs and commits to main does install semgrep on the runner and validates it.
