### ISSUE TITLE
Plugin validator fails unless release pipeline is run with go 1.21

### ISSUE THREAD

**Issue by helenosheaa** [grafana/plugin-validator#188]
When running the release pipeline on the community [grafana-flightsql-datasource ](https://github.com/influxdata/grafana-flightsql-datasource/blob/main/.github/workflows/release.yml)plugin I ran into the following error:

```
go: errors parsing go.mod:
/Users/user/influx/plugin-validator/go.mod:3: invalid go version '1.21.8': must match format 1.23
/Users/user/influx/plugin-validator/go.mod:5: unknown directive: toolchain
```

I updated the release pipeline from go 1.20 to go 1.21 to fix the problem.

It may be worth calling out on your documentation that this is now a requirement of running the plugin validator.

**Comment by tolzhabayev** [comment]
Hey @helenosheaa,
we are using the version in [go.mod file](https://github.com/grafana/plugin-validator/blob/main/go.mod#L3) to indicate the required version. We will add a note to the doc to check out the go.mod file as it is the source of truth.

**Comment by Ukochka** [comment]
`unknown directive: toolchain` is expected behaviour, because  version 1.20  doesn’t have that supported. To be able to run plugin validator you have to  use go version 1.21.1. This information can be found at `go.mod`
