### ISSUE TITLE
Validate that nested plugins are listed in the parent's plugin.json includes

### ISSUE THREAD

**Issue by wbrowne** [grafana/plugin-validator#215]
For example, https://github.com/grafana/grafana-zabbix is an app that bundles a backend datasource and a panel. The includes should look like the following (Note: `name` can be omitted - `type` and `path` are what's important):

```json
"includes": [
    {
      "type": "datasource",
      "name": "Zabbix data source",
      "path": "datasource/plugin.json"
    },
    {
      "type": "panel",
      "name": "Problems panel",
      "path": "panel-triggers/plugin.json"
    }
  ],
```

**Comment by academo** [comment]
Closed by https://github.com/grafana/plugin-validator/pull/217
