### ISSUE TITLE
Hosted version disappeared

### ISSUE THREAD

**Issue by simPod** [grafana/plugin-validator#23]
Hi, it was hosted here https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/ but it's gone now. Can I find it somewhere? Thanks!

**Comment by marcusolsson** [comment]
Yes, we finally got around to create a decent URL for it 😅 

https://plugin-validator.grafana.net

It's also documented in the README in case you need to find it again.

**Comment by simPod** [comment]
Thank you.

BTW in this repository it does not seem to be in readme 🤔 

![image](https://user-images.githubusercontent.com/327717/125781988-a7e83965-ba20-4f72-a92d-77ffab156654.png)

**Comment by marcusolsson** [comment]
Good catch! We should add it to that repository as well! 💯
