### ISSUE TITLE
README validation improvements

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/plugin-validator#251]
Based off the feedback we got through the developer interviews.

We could add additional warning to readme validaiton:
- warn if the image urls are not absolute in the src/README.md.
- warn if there are any comments in src/README.md.

**Comment by s4kh** [comment]
> warn if the image urls are not absolute in the src/README.md.

is handled as part of the [relativeLink rule](https://github.com/grafana/plugin-validator/blob/main/pkg/analysis/passes/brokenlinks/brokenlinks.go#L17) in [brokenlinks](https://github.com/grafana/plugin-validator/blob/main/pkg/analysis/passes/brokenlinks/brokenlinks.go) analyzer. But it is reported as **error** .

**Comment by tolzhabayev** [comment]
sovled via https://github.com/grafana/plugin-validator/pull/253
