### ISSUE TITLE
Deprecate plugincheck in favor of plugincheck2

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/plugin-validator#35]
- Remove `plugincheck` from the readme and only keep `plugincheck2`
- Show a message to migrate to `plugincheck2` every time it's ran. Do not remove code yet.
- Add a deprecation notice to the `readme.md` of the `plugincheck` pkg
- Mark code as deprecated https://stackoverflow.com/questions/7849663/how-do-you-mark-code-as-deprecated-in-go
- Search for usages of `plugincheck` in the wild:
- - https://cs.github.com/?scopeName=All+repos&scope=&q=plugincheck+language%3AYAML#
- - At least 14 plugins are currently using it

**Comment by academo** [comment]
@tolzhabayev since both of them are compatible can we start putting the plugincheck2 binary in place of plugincheck after a while?

**Comment by tolzhabayev** [comment]
Are they really replaceable / a drop-in replacement?

**Comment by academo** [comment]
> Are they really replaceable / a drop-in replacement?

The parameters are the same and the share the same configuration. I am not really sure why they were made as different projects. I'll ask around.

**Comment by tolzhabayev** [comment]
Ideally we should end up with one project that is versioned (like our go sdk) - we need to figure out what is better:
- Keep `plugincheck` and release a new version of it and deprecate `plugincheck2`
     - Means we would have to migrate everyone and their CI's, etc. to `plugincheck`
- Keep  `plugincheck2` and deprecate `plugincheck` which I would not change at all, also not place another binary into it - just leave as is
     - Means we would have to keep `plugincheck2` name forever and iterate on it using versioning. Naming might be a bit confusing.
     - Migrate everyone to use `plugincheck2`
