### ISSUE TITLE
Create an `npx` command to validate plugins

### ISSUE THREAD

**Issue by 6nv** [grafana/plugin-validator#71]
Similar to `npx @grafana/create-plugin` or `npx @grafana/sign-plugin`, it would be very useful to have a command to validate a plugin. Then we could add it to `package.json` and run `yarn validate` (for example) to test our plugins locally before pushing to a repository.

**Comment by academo** [comment]
Available here https://www.npmjs.com/package/@grafana/plugin-validator

Documentation on usage pending here https://github.com/grafana/plugin-validator/pull/88

**Comment by 6nv** [comment]
Great, thank you! I'm trying it out now, I think I just figured it out. These are the commands I used.

```sh
cp -r dist ventura-psychrometric-panel
zip -r ventura-psychrometric-panel.zip ventura-psychrometric-panel
npx @grafana/plugin-validator@latest -sourceCodeUri file://. ventura-psychrometric-panel.zip
```

And this is the output following:

```yml
warning: Binary for osv-scanner not found in PATH
detail: osv-scanner executable must be in your shell PATH.
error: Plugin version 1.0.0 is invalid.
detail: The submitted plugin version 1.0.0 is not greater than the latest published version 2.0.1 on grafana.com.
error: Valid license not found
detail: The provided license is not compatible with Grafana plugins. Please refer to https://grafana.com/licensing/ for more information.
warning: unsigned plugin
detail: MANIFEST.txt file not found. Please refer to the documentation for how to sign a plugin. https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/
```

I'm not sure what `osv-scanner` is. Am I missing a dependency? I am on MacOSX 13.2.1 by the way.

You might want to add some steps in the README on how to run this locally. I might still not have it completely correct, so feel free to correct me.

```sh
cp -r dist ${PLUGIN_ID}
zip -r ${PLUGIN_ID}.zip ${PLUGIN_ID}
npx @grafana/plugin-validator@latest -sourceCodeUri file://. ${PLUGIN_ID}.zip
```

**Comment by academo** [comment]
I updated the readme to have information about how to run the command: https://github.com/grafana/plugin-validator#with-npx

`osv-scanner` is a security tool to review your dependencies. you can install it if you want but it is optional https://github.com/google/osv-scanner

if you [run the validator with docker](https://github.com/grafana/plugin-validator#with-docker-recommended) you'll have all the security tools installed already.

**Comment by 6nv** [comment]
> I updated the readme to have information about how to run the command: https://github.com/grafana/plugin-validator#with-npx

I saw this - but it only shows how to do it for a previously published version on GH. I want to run it locally before pushing the code. I'm assuming I did it correctly since I got the output I was expecting.

**Comment by academo** [comment]
@6nv ah! I understand. Your instructions are about running the validator in your local development environment. Please feel free to submit a PR updating the README and I'll be happy to review it and merge it.

**Comment by 6nv** [comment]
Will do, thanks! @academo
