### ISSUE TITLE
Auto-update docker image

### ISSUE THREAD

**Issue by academo** [grafana/plugin-validator#75]
Look into auto updating the docker image and add it to the documentation 

https://hub.docker.com/r/grafana/plugin-validator-cli

**Comment by tolzhabayev** [comment]
Here is an example of how github suggests to do it using some github actions provided by docker:
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub

**Comment by academo** [comment]
The `.drone.yml` file will take care of this from now on.
