### ISSUE TITLE
Plugin dependencies bug

### ISSUE THREAD

**Issue by SergeiSporyshev** [grafana/plugin-validator#9]
Hi, @marcusolsson
I found bug in your validator
In my [case](https://grafana-plugins-web-vgmmyppaka-lz.a.run.app/?url=https://github.com/devopsprodigy/kubegraf/releases/download/v1.5.0.4/devopsprodigy-kubegraf-app-1.5.0.zip) i have message: dependencies.plugins.0: Invalid type. Expected: string, given: object
But [documentation](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#plugins) says, that it should be object

When i restarted grafana with plugin.dependencies like string, i have errors in grafana-logs like

t=2021-01-21T10:13:20+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="json: cannot unmarshal string into Go struct field PluginDependencies.dependencies.plugins of type plugins.PluginDependencyItem" pluginPath=/var/lib/grafana/plugins/devopsprodigy-kubegraf-app/dist

**Comment by marcusolsson** [comment]
Thank you for reporting this! I'll look into this today

**Comment by marcusolsson** [comment]
This is weird. It works if I run the CLI locally 🤔

**Comment by marcusolsson** [comment]
The bug was due to a config issue in the web app rather than the validator. Should be working on. Thanks for reporting this 🙏
